project:
  type: website
  render:
    - index.qmd
    - pydemo.qmd
  output-dir: docs

format:
  html:
    theme: cosmo
    toc: true

website:
  title: "testsite"
  navbar:
    left:
      - href: index.qmd
        text: "index"
      - href: pydemo.qmd
        text: "python demo"
  site-url: "https://guidoeco@guidoeco.github.io/Wurfel/" # makes site links work on your remote site

execute:
  freeze: auto
