project:
  type: website
  render:
    - index.qmd
    - pydemo.qmd
  output-dir: docs

website:
  title: "testsite"
  navbar:
    left:
      - href: pydemo.qmd
        text: "python demo"

format: html
website:
  site-url: "https://guidoeco.github.io/Wurfel/" # makes site links work on your remote site

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
