name: Render and Publish
on:
  push:
    branches:
      - main  # changes pushed to this branch will trigger a build.

jobs:
  build-deploy:
      name: build environment
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
          with:
            persist-credentials: true
        - name: set up python
          uses: actions/setup-python@v5
          with:
            python-version: "3.x"
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: check git environment
          run: |
            git config --list
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            version: 1.3.340
        - name: Publish to GitHub Pages (and render)
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages # rendered html files will be pushed here
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
